### PR TITLE
docs(README): Add missing quotation mark to README

### PR DESCRIPTION
**Pull request by bmulholland**
Self explanatory :)

### CODE REVIEW

**Comment by filipdutescu** [comment]
Thanks for the PR, nice catch! I saw you renamed your PR, which is nice, thank you, but you need to also reword your commit, to pass the CI.

Please follow the guide in [CONTRIBUTING.md](https://github.com/filipdutescu/renamer.nvim/blob/develop/CONTRIBUTING.md#commit-messages). Also do not forget to sign your commit (`git commit -s`).

**Comment by bmulholland** [comment]
I'll do it, but that means I have to do a full clone etc, which is a lot of overhead for a typo fix. The original commit was created with github's UI which meant it was only a few clicks, and probably an order of magnitude easier to do. I mention it because you may want to consider ways to allow simple, easy fixes like this in future.

**Comment by bmulholland** [comment]
GH's UI doesn't allow for amending commits, and I don't know if it does signed commits. Plus I'd have to know that I should use semantic commit messages and signing (i.e. read contributions doc), and TBH that's more depth than I usually look into for a typo fix.

**Comment by bmulholland** [comment]
And now lint is telling me that my syntax doesn't pass, even though it should match "<type>([optional scope]): <description>" that's in the doc: https://github.com/filipdutescu/renamer.nvim/blob/develop/CONTRIBUTING.md#commit-messages

So anyway, this is more trouble than it's worth. Sorry to be cranky about it, I'm a bit tired today and I just don't want to go through so much trouble to add a quotation mark.

Thanks for the plugin anyway, I've adopted it and appreciate the work :)

**Comment by filipdutescu** [comment]
What I could do *sometimes* is to amend the commit myself, but I do not know if it preserves the author. Since I merge from CLI, not from GH and pull the remote branches.

**Comment by bmulholland** [comment]
No it's totally cool, feel free to do whatever you want :). I just passed how much work I was willing to put into it. Thanks again for the plugin - and like I say, thanks for being chill with some crankiness on my behalf.

**Comment by filipdutescu** [comment]
I am just happy that you like the plugin and hope you keep enjoying it :D there is also no need for thanks, everyone has tiring/bad days and there is no gain in not being understanding. Hope you get well rested and take care :)

**Comment by filipdutescu** [comment]
I did not manage to figure out how to amend the commit message without changing the commit hash... But I did manage to preserve you as the author in ca8f013, hope that is fine by you.

**Comment by bmulholland** [comment]
Would have been fine without being an author, too :). Thanks for fixing it!

**Pull request closed without merging**
